// frontend/src/views/Dashboard.vue
<template>
  <div class="page-container">
    <!-- 页面标题 -->
    <div class="flex items-center justify-between mb-6 animate-in">
      <div>
        <h1 class="text-xl font-bold" style="color: var(--text-primary)">监控台</h1>
        <p class="text-sm mt-1" style="color: var(--text-secondary)">项目健康度实时总览 · {{ today }}</p>
      </div>
      <el-button type="primary" plain size="small" @click="fetchAll" :loading="loading">
        <el-icon class="mr-1"><Refresh /></el-icon>刷新数据
      </el-button>
      <el-button v-if="isAdmin" type="success" size="small" @click="projectCreateVisible = true">
        <el-icon class="mr-1"><Plus /></el-icon>新建项目
      </el-button>
    </div>

    <!-- 统计卡片 -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-5 mb-8">
      <div class="stat-card animate-in" style="animation-delay: 0.1s">
        <div class="flex items-center gap-3 mb-3">
          <div class="w-10 h-10 rounded-lg flex items-center justify-center" style="background: rgba(59,130,246,0.15)">
            <el-icon :size="20" color="#3b82f6"><DataBoard /></el-icon>
          </div>
          <span class="label">活跃项目</span>
        </div>
        <div class="number">{{ overview.total ?? '-' }}</div>
        <div class="flex gap-3 mt-2 text-xs">
          <span style="color: #22c55e">🟢 {{ overview.green_count ?? 0 }}</span>
          <span style="color: #eab308">🟡 {{ overview.yellow_count ?? 0 }}</span>
          <span style="color: #ef4444">🔴 {{ overview.red_count ?? 0 }}</span>
        </div>
      </div>

      <div class="stat-card animate-in" style="animation-delay: 0.2s">
        <div class="flex items-center gap-3 mb-3">
          <div class="w-10 h-10 rounded-lg flex items-center justify-center" style="background: rgba(168,85,247,0.15)">
            <el-icon :size="20" color="#a855f7"><Cpu /></el-icon>
          </div>
          <span class="label">今日 AI 日报</span>
        </div>
        <div class="number">{{ morningStats.total_reports ?? '-' }}</div>
        <div class="flex gap-3 mt-2 text-xs">
          <span style="color: #22c55e">✅ {{ morningStats.pass_count ?? 0 }}</span>
          <span style="color: #ef4444">❌ {{ morningStats.fail_count ?? 0 }}</span>
          <span style="color: var(--text-secondary)">均分 {{ morningStats.avg_score ?? '-' }}</span>
        </div>
      </div>

      <div class="stat-card animate-in" style="animation-delay: 0.3s">
        <div class="flex items-center gap-3 mb-3">
          <div class="w-10 h-10 rounded-lg flex items-center justify-center" style="background: rgba(239,68,68,0.15)">
            <el-icon :size="20" color="#ef4444"><WarningFilled /></el-icon>
          </div>
          <span class="label">未汇报 / 卡点</span>
        </div>
        <div class="number" :style="{ color: (missingMembers.length + riskAlerts.length) > 0 ? '#ef4444' : undefined }">
          {{ missingMembers.length }} / {{ riskAlerts.length }}
        </div>
        <div class="text-xs mt-2" style="color: var(--text-secondary)">
          需管理层关注介入
        </div>
      </div>
    </div>

    <!-- ═══ 晨报明细（AI 日报一览）═══ -->
    <div v-if="morningReports.length" class="mb-8 animate-in" style="animation-delay: 0.35s">
      <div class="section-title">📋 AI 日报明细（{{ morningBriefingDate }}）</div>
      <div class="grid grid-cols-1 gap-3">
        <div v-for="r in morningReports" :key="r.member"
             class="stat-card flex items-start gap-4"
             style="padding: 14px 18px">
          <!-- 评分 -->
          <div class="text-center flex-shrink-0" style="min-width: 48px">
            <div class="text-2xl font-bold" :style="{ color: scoreColor(r.ai_score) }">{{ r.ai_score ?? '-' }}</div>
            <el-tag :type="r.pass_check ? 'success' : 'danger'" size="small" round
                    style="margin-top: 4px; font-size: 10px">
              {{ r.pass_check ? '合格' : '退回' }}
            </el-tag>
          </div>
          <!-- 内容 -->
          <div class="flex-1 min-w-0">
            <div class="flex items-center gap-2 mb-1">
              <span class="font-semibold text-sm" style="color: var(--text-primary)">{{ r.member }}</span>
              <span class="text-xs" style="color: var(--text-secondary)">{{ r.department }}</span>
            </div>
            <div class="text-xs mb-1" style="color: var(--text-primary); line-height: 1.6">
              {{ r.tasks?.slice(0, 100) || '-' }}
            </div>
            <div class="text-xs" style="color: var(--text-secondary)">
              {{ r.ai_comment }}
            </div>
            <div v-if="r.blocker" class="text-xs mt-1" style="color: #ef4444">
              ⛔ 卡点：{{ r.blocker }}
            </div>
          </div>
          <!-- 进度 -->
          <div class="flex-shrink-0 text-right" style="min-width: 60px">
            <el-progress type="circle" :percentage="r.progress || 0" :width="44" :stroke-width="4"
                         :color="r.progress >= 80 ? '#22c55e' : r.progress >= 50 ? '#eab308' : '#ef4444'" />
          </div>
        </div>
      </div>
    </div>

    <!-- ═══ 未汇报名单 ═══ -->
    <div v-if="missingMembers.length" class="mb-8 animate-in" style="animation-delay: 0.4s">
      <div class="section-title">
        🔕 未汇报名单
        <el-tag type="warning" size="small" round>{{ missingMembers.length }}</el-tag>
      </div>
      <div class="stat-card">
        <div class="flex flex-wrap gap-3">
          <div v-for="m in missingMembers" :key="m.name"
               class="flex items-center gap-2 px-3 py-2 rounded-lg"
               style="background: var(--bg-secondary)">
            <el-avatar :size="28" style="background: linear-gradient(135deg, #94a3b8, #64748b); font-size: 12px">
              {{ m.name.charAt(0) }}
            </el-avatar>
            <div>
              <div class="text-xs font-semibold" style="color: var(--text-primary)">{{ m.name }}</div>
              <div class="text-xs" style="color: var(--text-secondary)">{{ m.department }}</div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- 项目列表 -->
    <div class="mb-8 animate-in" style="animation-delay: 0.45s">
      <div class="section-title">项目健康矩阵</div>
      <div class="grid grid-cols-1 gap-4">
        <div v-for="p in projects" :key="p.project_id"
             class="stat-card cursor-pointer flex items-center gap-5"
             @click="$router.push(`/project/${p.project_id}`)">
          <!-- 健康指示灯 -->
          <div class="w-3 h-3 rounded-full flex-shrink-0"
               :style="{ background: healthColor(p.health_status) }" />
          <!-- 项目信息 -->
          <div class="flex-1 min-w-0">
            <div class="font-semibold text-sm" style="color: var(--text-primary)">
              {{ p.code }} · {{ p.name }}
            </div>
            <div class="text-xs mt-1" style="color: var(--text-secondary)">
              第{{ p.current_stage }}阶段「{{ p.stage_name }}」 · {{ p.track === 'dual' ? '软硬双轨' : p.track }}
            </div>
          </div>
          <!-- 健康分数 -->
          <div class="text-right flex-shrink-0">
            <div class="text-lg font-bold" :style="{ color: healthColor(p.health_status) }">
              {{ p.health_score }}
            </div>
            <div class="text-xs" style="color: var(--text-secondary)">
              距交付 {{ p.days_to_deadline }}天
            </div>
          </div>
          <el-icon color="#4b5563"><ArrowRight /></el-icon>
        </div>
      </div>
    </div>

    <!-- 风险阻碍池 -->
    <div class="animate-in" style="animation-delay: 0.5s">
      <div class="section-title">
        风险阻碍池
        <el-tag v-if="riskAlerts.length" type="danger" size="small" round>{{ riskAlerts.length }}</el-tag>
      </div>
      <div v-if="riskAlerts.length === 0" class="text-center py-12" style="color: var(--text-secondary)">
        <el-icon :size="48"><CircleCheckFilled /></el-icon>
        <p class="mt-3">暂无未解除的风险卡点 🎉</p>
      </div>
      <div v-else class="grid grid-cols-1 gap-4">
        <div v-for="alert in riskAlerts" :key="alert.id" class="risk-card flex items-start gap-4">
          <el-icon :size="20" color="#ef4444" class="mt-0.5"><WarningFilled /></el-icon>
          <div class="flex-1 min-w-0">
            <div class="font-semibold text-sm" style="color: var(--text-primary)">{{ alert.title }}</div>
            <div class="text-xs mt-1" style="color: var(--text-secondary)">
              {{ alert.department }} · {{ alert.reporter }} · {{ alert.created_at }}
            </div>
            <div class="text-xs mt-2" style="color: var(--text-secondary)">{{ alert.description }}</div>
          </div>
          <el-button type="success" size="small" plain @click="resolveAlert(alert.id)">
            标记解决
          </el-button>
        </div>
      </div>
    </div>

    <!-- ═══ 新建项目弹窗 ═══ -->
    <el-dialog v-model="projectCreateVisible" title="新建项目" width="480px" :close-on-click-modal="false">
      <el-form label-width="80px" label-position="left">
        <el-form-item label="项目名称" required>
          <el-input v-model="projectForm.name" placeholder="例如：206样机研发及落地" />
        </el-form-item>
        <el-form-item label="项目编号" required>
          <el-input v-model="projectForm.code" placeholder="P2026-002" />
        </el-form-item>
        <el-form-item label="轨道">
          <el-select v-model="projectForm.track" style="width:100%">
            <el-option label="软硬双轨" value="dual" />
            <el-option label="纯软件" value="software" />
            <el-option label="纯硬件" value="hardware" />
          </el-select>
        </el-form-item>
        <el-form-item label="计划交付">
          <el-date-picker v-model="projectForm.planned_launch_date" type="date" value-format="YYYY-MM-DD" style="width:100%" />
        </el-form-item>
        <el-form-item label="预算（元）">
          <el-input-number v-model="projectForm.budget_total" :min="0" :step="10000" style="width:100%" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="projectCreateVisible = false">取消</el-button>
        <el-button type="primary" @click="handleCreateProject" :loading="projectSubmitting"
                   style="background: linear-gradient(135deg, #3b82f6, #6366f1); border: none">立项</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted } from 'vue'
import { getMorningBriefing, getRiskAlerts } from '../api/dashboard'
import { getProjectsOverview, createProject } from '../api/projects'
import { Refresh, DataBoard, Cpu, WarningFilled, ArrowRight, CircleCheckFilled, Plus } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { useAuthStore } from '../stores/auth'

const authStore = useAuthStore()
const isAdmin = computed(() => authStore.isAdmin)

const loading = ref(false)
const today = new Date().toLocaleDateString('zh-CN', { month: 'long', day: 'numeric', weekday: 'long' })

const overview = ref<any>({})
const projects = ref<any[]>([])
const riskAlerts = ref<any[]>([])

// ── 晨报数据 ──
const morningStats = ref<any>({})
const morningReports = ref<any[]>([])
const missingMembers = ref<any[]>([])
const morningBriefingDate = ref('')

function healthColor(status: string) {
  return { green: '#22c55e', yellow: '#eab308', red: '#ef4444', locked: '#4b5563' }[status] || '#4b5563'
}

function scoreColor(score: number | null) {
  if (score == null) return 'var(--text-secondary)'
  if (score >= 90) return '#22c55e'
  if (score >= 60) return '#eab308'
  return '#ef4444'
}

async function fetchAll() {
  loading.value = true
  try {
    const [ov, br, ra] = await Promise.allSettled([
      getProjectsOverview(),
      getMorningBriefing(),
      getRiskAlerts(),
    ])
    if (ov.status === 'fulfilled') {
      const data = ov.value as any
      overview.value = data
      projects.value = data.projects || []
    }
    if (br.status === 'fulfilled') {
      const data = br.value as any
      morningStats.value = data.stats || {}
      morningReports.value = data.reports || []
      missingMembers.value = data.missing_members || []
      morningBriefingDate.value = data.report_date || ''
    }
    if (ra.status === 'fulfilled') {
      riskAlerts.value = (ra.value as any[]).filter((a: any) => a.status === 'unresolved')
    }
  } finally {
    loading.value = false
  }
}

async function resolveAlert(id: string) {
  ElMessage.success('已标记为已解决')
  riskAlerts.value = riskAlerts.value.filter(a => a.id !== id)
}

// ── 新建项目 ──
const projectCreateVisible = ref(false)
const projectSubmitting = ref(false)
const projectForm = reactive({
  name: '',
  code: '',
  track: 'dual',
  planned_launch_date: '',
  budget_total: 100000,
})

async function handleCreateProject() {
  projectSubmitting.value = true
  try {
    await createProject(projectForm)
    ElMessage.success(`项目 ${projectForm.code} 立项成功`)
    projectCreateVisible.value = false
    fetchAll()
  } catch (e: any) {
    ElMessage.error(e?.response?.data?.detail || '立项失败')
  } finally {
    projectSubmitting.value = false
  }
}

onMounted(fetchAll)
</script>

// frontend/src/app/dashboard/page.tsx
/**
 * app/dashboard/page.tsx — 监控台 (1:1 port from Vue Dashboard.vue)
 *
 * Sections:
 *   1. 统计卡片 (活跃项目 / AI 日报 / 未汇报+卡点)
 *   2. AI 日报明细表
 *   3. 未汇报名单
 *   4. 项目健康矩阵
 *   5. 风险阻碍池
 *   6. 新建项目弹窗
 */
'use client'

import { useState, useEffect, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { useAuthStore } from '@/stores/use-auth-store'
import { getMorningBriefing, getRiskAlerts, getTempTicketSummary } from '@/api/dashboard'
import { getProjectsOverview, createProject } from '@/api/projects'
import { toast } from 'sonner'
import {
  LayoutDashboard,
  Cpu,
  AlertTriangle,
  ArrowRight,
  CheckCircle,
  RefreshCw,
  Plus,
  Ticket,
  Trophy,
} from 'lucide-react'

export default function DashboardPage() {
  const router = useRouter()
  const { isAdmin } = useAuthStore()
  const [loading, setLoading] = useState(false)
  const today = new Date().toLocaleDateString('zh-CN', {
    month: 'long',
    day: 'numeric',
    weekday: 'long',
  })

  const [overview, setOverview] = useState<any>({})
  const [projects, setProjects] = useState<any[]>([])
  const [riskAlerts, setRiskAlerts] = useState<any[]>([])
  const [morningStats, setMorningStats] = useState<any>({})
  const [morningReports, setMorningReports] = useState<any[]>([])
  const [missingMembers, setMissingMembers] = useState<any[]>([])
  const [morningBriefingDate, setMorningBriefingDate] = useState('')
  // V2.3 临时工单看板数据
  const [tempSummary, setTempSummary] = useState<any>(null)

  // 新建项目弹窗
  const [showCreate, setShowCreate] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [projectForm, setProjectForm] = useState({
    name: '',
    code: '',
    track: 'dual',
    planned_launch_date: '',
    budget_total: 100000,
  })

  const healthColor = (status: string) =>
    ({ green: '#22c55e', yellow: '#eab308', red: '#ef4444', locked: '#4b5563' }[status] || '#4b5563')

  const scoreColor = (score: number | null) => {
    if (score == null) return 'var(--color-text-secondary)'
    if (score >= 90) return '#22c55e'
    if (score >= 60) return '#eab308'
    return '#ef4444'
  }

  const fetchAll = useCallback(async () => {
    setLoading(true)
    try {
      const [ov, br, ra, tt] = await Promise.allSettled([
        getProjectsOverview(),
        getMorningBriefing(),
        getRiskAlerts(),
        getTempTicketSummary({ top_n: 5 }),
      ])
      if (ov.status === 'fulfilled') {
        const data = ov.value as any
        setOverview(data)
        setProjects(data.projects || [])
      }
      if (br.status === 'fulfilled') {
        const data = br.value as any
        setMorningStats(data.stats || {})
        setMorningReports(data.reports || [])
        setMissingMembers(data.missing_members || [])
        setMorningBriefingDate(data.report_date || '')
      }
      if (ra.status === 'fulfilled') {
        setRiskAlerts((ra.value as unknown as any[]).filter((a: any) => a.status === 'unresolved'))
      }
      if (tt.status === 'fulfilled') {
        setTempSummary(tt.value as any)
      }
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    fetchAll()
  }, [fetchAll])

  async function handleCreateProject() {
    setSubmitting(true)
    try {
      await createProject(projectForm)
      toast.success(`项目 ${projectForm.code} 立项成功`)
      setShowCreate(false)
      fetchAll()
    } catch (e: any) {
      toast.error(e?.response?.data?.detail || '立项失败')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="page-container">
      {/* 页面标题 */}
      <div className="flex items-center justify-between mb-6 animate-in">
        <div>
          <h1 className="text-xl font-bold" style={{ color: 'var(--color-text-primary)' }}>
            监控台
          </h1>
          <p className="text-sm mt-1" style={{ color: 'var(--color-text-secondary)' }}>
            项目健康度实时总览 · {today}
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={fetchAll}
            disabled={loading}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors"
            style={{
              border: '1px solid var(--color-brand-blue)',
              color: 'var(--color-brand-blue)',
            }}
          >
            <RefreshCw size={14} className={loading ? 'animate-spin' : ''} />
            刷新数据
          </button>
          {isAdmin && (
            <button
              onClick={() => setShowCreate(true)}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-white"
              style={{ background: 'var(--color-status-green)' }}
            >
              <Plus size={14} />
              新建项目
            </button>
          )}
        </div>
      </div>

      {/* 统计卡片 */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mb-8">
        {/* 活跃项目 */}
        <div className="stat-card animate-in" style={{ animationDelay: '0.1s' }}>
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 rounded-lg flex items-center justify-center" style={{ background: 'rgba(59,130,246,0.15)' }}>
              <LayoutDashboard size={20} color="#3b82f6" />
            </div>
            <span className="text-xs" style={{ color: 'var(--color-text-secondary)' }}>活跃项目</span>
          </div>
          <div className="text-2xl font-bold" style={{ color: 'var(--color-text-primary)' }}>
            {overview.total ?? '-'}
          </div>
          <div className="flex gap-3 mt-2 text-xs">
            <span style={{ color: '#22c55e' }}>🟢 {overview.green_count ?? 0}</span>
            <span style={{ color: '#eab308' }}>🟡 {overview.yellow_count ?? 0}</span>
            <span style={{ color: '#ef4444' }}>🔴 {overview.red_count ?? 0}</span>
          </div>
        </div>

        {/* AI 日报 */}
        <div className="stat-card animate-in" style={{ animationDelay: '0.2s' }}>
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 rounded-lg flex items-center justify-center" style={{ background: 'rgba(168,85,247,0.15)' }}>
              <Cpu size={20} color="#a855f7" />
            </div>
            <span className="text-xs" style={{ color: 'var(--color-text-secondary)' }}>今日 AI 日报</span>
          </div>
          <div className="text-2xl font-bold" style={{ color: 'var(--color-text-primary)' }}>
            {morningStats.total_reports ?? '-'}
          </div>
          <div className="flex gap-3 mt-2 text-xs">
            <span style={{ color: '#22c55e' }}>✅ {morningStats.pass_count ?? 0}</span>
            <span style={{ color: '#ef4444' }}>❌ {morningStats.fail_count ?? 0}</span>
            <span style={{ color: 'var(--color-text-secondary)' }}>均分 {morningStats.avg_score ?? '-'}</span>
          </div>
        </div>

        {/* 未汇报 / 卡点 */}
        <div className="stat-card animate-in" style={{ animationDelay: '0.3s' }}>
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 rounded-lg flex items-center justify-center" style={{ background: 'rgba(239,68,68,0.15)' }}>
              <AlertTriangle size={20} color="#ef4444" />
            </div>
            <span className="text-xs" style={{ color: 'var(--color-text-secondary)' }}>未汇报 / 卡点</span>
          </div>
          <div
            className="text-2xl font-bold"
            style={{ color: (missingMembers.length + riskAlerts.length) > 0 ? '#ef4444' : 'var(--color-text-primary)' }}
          >
            {missingMembers.length} / {riskAlerts.length}
          </div>
          <div className="text-xs mt-2" style={{ color: 'var(--color-text-secondary)' }}>
            需管理层关注介入
          </div>
        </div>
      </div>

      {/* AI 日报明细 */}
      {morningReports.length > 0 && (
        <div className="mb-8 animate-in" style={{ animationDelay: '0.35s' }}>
          <div className="section-title">📋 AI 日报明细（{morningBriefingDate}）</div>
          <div className="grid grid-cols-1 gap-3">
            {morningReports.map((r: any) => (
              <div key={r.member} className="stat-card flex items-start gap-4" style={{ padding: '14px 18px' }}>
                <div className="text-center shrink-0" style={{ minWidth: 48 }}>
                  <div className="text-2xl font-bold" style={{ color: scoreColor(r.ai_score) }}>
                    {r.ai_score ?? '-'}
                  </div>
                  <span
                    className="inline-block mt-1 px-2 py-0.5 rounded-full text-[10px] font-medium"
                    style={{
                      background: r.pass_check ? 'rgba(34,197,94,0.15)' : 'rgba(239,68,68,0.15)',
                      color: r.pass_check ? '#22c55e' : '#ef4444',
                    }}
                  >
                    {r.pass_check ? '合格' : '退回'}
                  </span>
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="font-semibold text-sm" style={{ color: 'var(--color-text-primary)' }}>{r.member}</span>
                    <span className="text-xs" style={{ color: 'var(--color-text-secondary)' }}>{r.department}</span>
                  </div>
                  <div className="text-xs mb-1" style={{ color: 'var(--color-text-primary)', lineHeight: 1.6 }}>
                    {r.tasks?.slice(0, 100) || '-'}
                  </div>
                  <div className="text-xs" style={{ color: 'var(--color-text-secondary)' }}>{r.ai_comment}</div>
                  {r.blocker && (
                    <div className="text-xs mt-1" style={{ color: '#ef4444' }}>⛔ 卡点：{r.blocker}</div>
                  )}
                </div>
                <div className="shrink-0 text-right" style={{ minWidth: 50 }}>
                  <div
                    className="w-11 h-11 rounded-full border-[3px] flex items-center justify-center text-xs font-bold"
                    style={{
                      borderColor: (r.progress || 0) >= 80 ? '#22c55e' : (r.progress || 0) >= 50 ? '#eab308' : '#ef4444',
                      color: 'var(--color-text-primary)',
                    }}
                  >
                    {r.progress || 0}%
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 未汇报名单 */}
      {missingMembers.length > 0 && (
        <div className="mb-8 animate-in" style={{ animationDelay: '0.4s' }}>
          <div className="section-title">
            🔕 未汇报名单
            <span className="px-2 py-0.5 rounded-full text-[10px] font-medium" style={{ background: 'rgba(234,179,8,0.15)', color: '#eab308' }}>
              {missingMembers.length}
            </span>
          </div>
          <div className="stat-card">
            <div className="flex flex-wrap gap-3">
              {missingMembers.map((m: any) => (
                <div key={m.name} className="flex items-center gap-2 px-3 py-2 rounded-lg" style={{ background: 'var(--color-bg-secondary)' }}>
                  <div className="w-7 h-7 rounded-full flex items-center justify-center text-white text-xs" style={{ background: 'linear-gradient(135deg, #94a3b8, #64748b)' }}>
                    {m.name.charAt(0)}
                  </div>
                  <div>
                    <div className="text-xs font-semibold" style={{ color: 'var(--color-text-primary)' }}>{m.name}</div>
                    <div className="text-xs" style={{ color: 'var(--color-text-secondary)' }}>{m.department}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* V2.3 临时工单看板(两张卡片:TOP5 + 占比) */}
      {tempSummary && (
        <div className="mb-8 animate-in" style={{ animationDelay: '0.42s' }}>
          <div className="section-title flex items-center gap-2">
            <Ticket size={16} color="#a855f7" />
            临时工单看板
            <span className="text-[10px] font-normal" style={{ color: 'var(--color-text-secondary)' }}>
              （{tempSummary.window?.start} → {tempSummary.window?.end} · 口径:每条日报 ≈ {tempSummary.hours_per_report}h）
            </span>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            {/* 左卡:本月工时 TOP N */}
            <div className="stat-card">
              <div className="flex items-center gap-2 mb-3">
                <Trophy size={16} color="#a855f7" />
                <span className="text-sm font-medium" style={{ color: 'var(--color-text-primary)' }}>
                  本月临时工单工时 TOP {tempSummary.top_members?.length || 0}
                </span>
              </div>
              {tempSummary.top_members?.length ? (
                <div className="space-y-2">
                  {tempSummary.top_members.map((m: any, i: number) => {
                    const maxHours = tempSummary.top_members[0]?.hours_estimated || 1
                    const pct = Math.round((m.hours_estimated / maxHours) * 100)
                    return (
                      <div key={m.user_id} className="flex items-center gap-3">
                        <div
                          className="w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-bold shrink-0"
                          style={{
                            background:
                              i === 0
                                ? '#fbbf24'
                                : i === 1
                                  ? '#94a3b8'
                                  : i === 2
                                    ? '#d97706'
                                    : 'var(--color-bg-secondary)',
                            color: i < 3 ? '#fff' : 'var(--color-text-secondary)',
                          }}
                        >
                          {i + 1}
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center justify-between text-xs mb-1">
                            <span style={{ color: 'var(--color-text-primary)' }}>
                              {m.user_name}
                              <span className="ml-1.5" style={{ color: 'var(--color-text-secondary)' }}>
                                · {m.department || '—'}
                              </span>
                            </span>
                            <span style={{ color: '#a855f7', fontWeight: 600 }}>
                              {m.hours_estimated}h
                              <span className="ml-1 text-[10px]" style={{ color: 'var(--color-text-secondary)' }}>
                                ({m.report_count} 条)
                              </span>
                            </span>
                          </div>
                          <div
                            className="h-1.5 rounded-full"
                            style={{ background: 'var(--color-bg-secondary)' }}
                          >
                            <div
                              className="h-full rounded-full transition-all"
                              style={{
                                width: `${pct}%`,
                                background: 'linear-gradient(90deg, #a855f7, #6366f1)',
                              }}
                            />
                          </div>
                        </div>
                      </div>
                    )
                  })}
                </div>
              ) : (
                <div className="text-xs py-6 text-center" style={{ color: 'var(--color-text-secondary)' }}>
                  本月暂无临时工单数据
                </div>
              )}
            </div>

            {/* 右卡:临时 vs 主干 工时占比环形图 */}
            <div className="stat-card">
              <div className="flex items-center gap-2 mb-3">
                <span className="text-sm font-medium" style={{ color: 'var(--color-text-primary)' }}>
                  临时工单 vs 主干项目 · 工时占比
                </span>
              </div>
              {tempSummary.ratio?.total_hours > 0 ? (
                <div className="flex items-center gap-6">
                  {/* conic-gradient 环形图 */}
                  <div
                    className="w-32 h-32 rounded-full relative shrink-0"
                    style={{
                      background: `conic-gradient(#a855f7 0% ${tempSummary.ratio.temp_pct}%, #3b82f6 ${tempSummary.ratio.temp_pct}% 100%)`,
                    }}
                  >
                    <div
                      className="absolute inset-3 rounded-full flex flex-col items-center justify-center"
                      style={{ background: 'var(--color-bg-card)' }}
                    >
                      <div className="text-lg font-bold" style={{ color: '#a855f7' }}>
                        {tempSummary.ratio.temp_pct}%
                      </div>
                      <div className="text-[10px]" style={{ color: 'var(--color-text-secondary)' }}>
                        临时占比
                      </div>
                    </div>
                  </div>
                  {/* 图例 */}
                  <div className="flex-1 space-y-3 text-xs">
                    <div className="flex items-center justify-between">
                      <span className="flex items-center gap-2" style={{ color: 'var(--color-text-primary)' }}>
                        <span className="w-3 h-3 rounded-sm" style={{ background: '#a855f7' }} />
                        🎫 临时工单
                      </span>
                      <span style={{ color: '#a855f7', fontWeight: 600 }}>
                        {tempSummary.ratio.temp_hours}h
                      </span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="flex items-center gap-2" style={{ color: 'var(--color-text-primary)' }}>
                        <span className="w-3 h-3 rounded-sm" style={{ background: '#3b82f6' }} />
                        📁 主干项目
                      </span>
                      <span style={{ color: '#3b82f6', fontWeight: 600 }}>
                        {tempSummary.ratio.main_hours}h
                      </span>
                    </div>
                    <div className="pt-2 mt-2 text-[11px]" style={{ borderTop: '1px solid var(--color-border-subtle)', color: 'var(--color-text-secondary)' }}>
                      合计 <span style={{ color: 'var(--color-text-primary)', fontWeight: 600 }}>{tempSummary.ratio.total_hours}h</span>
                      {tempSummary.ratio.temp_pct > 30 && (
                        <span className="block mt-1" style={{ color: '#eab308' }}>
                          ⚠️ 临时工单占比偏高,建议关注主干推进
                        </span>
                      )}
                    </div>
                  </div>
                </div>
              ) : (
                <div className="text-xs py-6 text-center" style={{ color: 'var(--color-text-secondary)' }}>
                  本月暂无项目维度的工时数据
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* 项目健康矩阵 */}
      <div className="mb-8 animate-in" style={{ animationDelay: '0.45s' }}>
        <div className="section-title">项目健康矩阵</div>
        <div className="grid grid-cols-1 gap-4">
          {projects.map((p: any) => (
            <div
              key={p.project_id}
              className="stat-card cursor-pointer flex items-center gap-5"
              onClick={() => router.push(`/project/${p.project_id}`)}
            >
              <div className="w-3 h-3 rounded-full shrink-0" style={{ background: healthColor(p.health_status) }} />
              <div className="flex-1 min-w-0">
                <div className="font-semibold text-sm" style={{ color: 'var(--color-text-primary)' }}>
                  {p.code} · {p.name}
                </div>
                <div className="text-xs mt-1" style={{ color: 'var(--color-text-secondary)' }}>
                  第{p.current_stage}阶段「{p.stage_name}」 · {p.track === 'dual' ? '软硬双轨' : p.track}
                </div>
              </div>
              <div className="text-right shrink-0">
                <div className="text-lg font-bold" style={{ color: healthColor(p.health_status) }}>{p.health_score}</div>
                <div className="text-xs" style={{ color: 'var(--color-text-secondary)' }}>距交付 {p.days_to_deadline}天</div>
              </div>
              <ArrowRight size={16} color="#4b5563" />
            </div>
          ))}
        </div>
      </div>

      {/* 风险阻碍池 */}
      <div className="animate-in" style={{ animationDelay: '0.5s' }}>
        <div className="section-title">
          风险阻碍池
          {riskAlerts.length > 0 && (
            <span className="px-2 py-0.5 rounded-full text-[10px] font-medium" style={{ background: 'rgba(239,68,68,0.15)', color: '#ef4444' }}>
              {riskAlerts.length}
            </span>
          )}
        </div>
        {riskAlerts.length === 0 ? (
          <div className="text-center py-12" style={{ color: 'var(--color-text-secondary)' }}>
            <CheckCircle size={48} className="mx-auto mb-3 opacity-50" />
            <p>暂无未解除的风险卡点 🎉</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 gap-4">
            {riskAlerts.map((alert: any) => (
              <div key={alert.id} className="stat-card flex items-start gap-4">
                <AlertTriangle size={20} color="#ef4444" className="mt-0.5 shrink-0" />
                <div className="flex-1 min-w-0">
                  <div className="font-semibold text-sm" style={{ color: 'var(--color-text-primary)' }}>{alert.title}</div>
                  <div className="text-xs mt-1" style={{ color: 'var(--color-text-secondary)' }}>
                    {alert.department} · {alert.reporter} · {alert.created_at}
                  </div>
                  <div className="text-xs mt-2" style={{ color: 'var(--color-text-secondary)' }}>{alert.description}</div>
                </div>
                <button
                  onClick={() => {
                    toast.success('已标记为已解决')
                    setRiskAlerts((prev) => prev.filter((a) => a.id !== alert.id))
                  }}
                  className="shrink-0 px-3 py-1.5 rounded-lg text-xs font-medium"
                  style={{ border: '1px solid var(--color-status-green)', color: 'var(--color-status-green)' }}
                >
                  标记解决
                </button>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* 新建项目弹窗 */}
      {showCreate && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" onClick={() => setShowCreate(false)}>
          <div
            className="w-full max-w-md rounded-2xl p-6"
            style={{ background: 'var(--color-bg-card)', border: '1px solid var(--color-border-subtle)' }}
            onClick={(e) => e.stopPropagation()}
          >
            <h2 className="text-lg font-semibold mb-5" style={{ color: 'var(--color-text-primary)' }}>新建项目</h2>
            <div className="space-y-4">
              {[
                { label: '项目名称', key: 'name', placeholder: '例如：206样机研发及落地', type: 'text' },
                { label: '项目编号', key: 'code', placeholder: 'P2026-002', type: 'text' },
              ].map((f) => (
                <div key={f.key}>
                  <label className="block text-xs mb-1.5 font-medium" style={{ color: 'var(--color-text-secondary)' }}>{f.label}</label>
                  <input
                    type={f.type}
                    value={(projectForm as any)[f.key]}
                    onChange={(e) => setProjectForm({ ...projectForm, [f.key]: e.target.value })}
                    placeholder={f.placeholder}
                    className="w-full px-3 py-2 rounded-lg text-sm outline-none"
                    style={{ background: 'var(--color-bg-secondary)', border: '1px solid var(--color-border-subtle)', color: 'var(--color-text-primary)' }}
                  />
                </div>
              ))}
              <div>
                <label className="block text-xs mb-1.5 font-medium" style={{ color: 'var(--color-text-secondary)' }}>轨道</label>
                <select
                  value={projectForm.track}
                  onChange={(e) => setProjectForm({ ...projectForm, track: e.target.value })}
                  className="w-full px-3 py-2 rounded-lg text-sm outline-none"
                  style={{ background: 'var(--color-bg-secondary)', border: '1px solid var(--color-border-subtle)', color: 'var(--color-text-primary)' }}
                >
                  <option value="dual">软硬双轨</option>
                  <option value="software">纯软件</option>
                  <option value="hardware">纯硬件</option>
                </select>
              </div>
              <div>
                <label className="block text-xs mb-1.5 font-medium" style={{ color: 'var(--color-text-secondary)' }}>计划交付</label>
                <input
                  type="date"
                  value={projectForm.planned_launch_date}
                  onChange={(e) => setProjectForm({ ...projectForm, planned_launch_date: e.target.value })}
                  className="w-full px-3 py-2 rounded-lg text-sm outline-none"
                  style={{ background: 'var(--color-bg-secondary)', border: '1px solid var(--color-border-subtle)', color: 'var(--color-text-primary)' }}
                />
              </div>
            </div>
            <div className="flex justify-end gap-3 mt-6">
              <button
                onClick={() => setShowCreate(false)}
                className="px-4 py-2 rounded-lg text-sm"
                style={{ color: 'var(--color-text-secondary)', border: '1px solid var(--color-border-subtle)' }}
              >
                取消
              </button>
              <button
                onClick={handleCreateProject}
                disabled={submitting}
                className="px-4 py-2 rounded-lg text-sm text-white font-medium disabled:opacity-60"
                style={{ background: 'linear-gradient(135deg, #3b82f6, #6366f1)' }}
              >
                {submitting ? '提交中...' : '立项'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
